version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.7
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "1212:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_host
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_password
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password